[package]
name = "bulk_upload_gdrive"
version = "0.1.0"
edition = "2024"

[dependencies]
google-drive3 = "*"
tokio = { version = "1.0", features = ["full"] }
serde = "1.0"
serde_json = "1.0"
futures = "*"
mime = "0.3"
anyhow = "1.0.98"
clap = { version = "^4.5", features = ["derive"] }
